### ISSUE TITLE
cannot find the psd file 

### ISSUE THREAD

**Issue by menaka1234** [WorthyD/WorthyD-Cutout-Demo#1]
please provide the link to doanload the PSD file. The link you have provided does not show a button to doanload the template

Sorry , found out that it is a premium design now. Thanks

**Comment by WorthyD** [comment]
@menaka1234 I was out of town when you posted this. 

Sorry, I'm working with someone to get a new PSD that we can use and I'll most likely create a new video series on it.

**Comment by rooh-e-asad** [comment]
i need this psd kindly solve this problem
